- .github/workflows/copy-workflow.yml
- workflow-templates/autorebase.yml
This is useful in repositories where the update of a workflow initially
fails, and the problem is subsequently fixed. It's necessary to rebase
the PR updating the workflow to make sure that all tests now actually
pass.
The new workflow (which will distribited to every participating repo)
achieves this by running on every issue comment, and triggers a rebase
if the comment was made on a PR opened by ipldbot, and it contains the
keywords "@ipldbot rebase".
> add a workflow to manually trigger a rebase of a PR opened by ipldbot

- .github/workflows/copy-workflow.yml
- workflow-templates/automerge.yml
This workflow aims to reduce the overhead of changing on our workflows. For example, we don't want to manually merge ipldbot's PRs that update the Go version every 6 months across all repos.
The `automerge` workflow runs in every participating repo and automatically merges any PR authored by ipldbot, as soon as (and only if) all checks succeed.
> add a workflow to automatically merge ipldbot's PRs

- workflow-templates/autorebase.yml
Sorry, looks like I forgot that one in #15. 
Looks like we need a GitHub Action to check our GitHub Actions ;) (just kidding)
> use commit hash to include 3rd party GitHub Actions in autorebase

- .github/workflows/copy-workflow.yml
Fixes #9.
The PRs we generate in child repositories should be more meaningful. Currently, we just link to the commit SHA in this repo. Instead, we should:
1. link to the PR that introduced the change (in this repo)
2. use the title of the PR in the commit message
3. use the title of the PR in the title of the PR in the child repo
Obviously, this requires us to make all changes to this repo via PRs. This is a good idea anyway. I turned on branch protection for `master` here.
Before:
After:
> generate a more useful commit message and PR description

- .github/workflows/check-3rd-party.sh
- .github/workflows/check-3rd-party.yml
As suggested by @mvdan in https://github.com/ipld/.github/pull/18#pullrequestreview-599396076.
Test failing because the copy workflow hasn't been updated yet (see #21).
> add a workflow to check that 3rd party actions are included by hash

- workflow-templates/go-check.yml
Fixes #6.
Run `go vet` and `staticcheck` without any involvement of golangci-lint. golangci-lint is a quite complicated beast, and we're probably better off just running the tools ourselves.
See https://github.com/marten-seemann-test/target/pull/33 for a demo of this workflow.
This has been blocked by the problems with staticcheck for way too long. I'm now using a regex to fix the output, such that GitHub Annotations will pick up the path. All we need to do is transform `cmd/main.go:5:6: func build is unused (U1000)` to `./cmd/main.go:5:6: func build is unused (U1000)`.
> run go vet and staticcheck in go-check

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
GitHub Actions limits the number of jobs in a matrix to 256. We create one job per repository and per file that we're copying. Therefore at the moment we're limited to 256/4 = 64 repositories.
This PR uses the [repository dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) function. In a nutshell, this feature allows us to emit a custom event named `copy-workflow`. We can then define another workflow that's triggered by this event.
The `dispatch.yml` workflow parses the `config.json` file (which contains a list of all participating repos). It batches the repositories into batches of 50: https://github.com/ipld/.github/blob/adb77431ecc3416bd1635e1f5bbcc640e41405f0/.github/workflows/dispatch.yml#L24-L25
For example, if we had 500 …
> make it possible to use this workflow with > 64 repos

- .github/workflows/copy-workflow.yml
In https://github.com/protocol/.github/issues/36#issuecomment-809463015, @mvdan suggested to only create a single PR per target repo, consisting of multiple commits, one for each file that was changed.
This will significantly reduce the noise of introducing this workflow to new repositories, as we're only opening a single PR instead of 4. It will also allow us to push changes to more repositories before triggering GitHub's abuse detection mechanism.
> only create a single PR per target repo

- .github/workflows/copy-workflow.yml
As suggested by @aschmahmann, when we first deploy the `go-test` workflow to repositories, we should disable Travis and CircleCI. The copy workflow adds commits deleting `.travis.yml` and `.circleci/`, IF `.github/workflows/go-test.yml` doesn't exist yet (and thus will be added in the same PR).
> remove Travis and CircleCI configs on first deployment of test workflow

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
Fixes #49.
Our current logic is slightly wrong: We build the (last) commit of a PR, not the merge commit. We did this because it allows us easy access to the PR title, which GitHub doesn't give us for a push to master.
Furthermore, since we were building a PR, GitHub would only give us access to the repository's secrets if we weren't building from a fork.
This PR changes the logic: We now build every push on master. As master is branch-protected, this means we'll only build merge commits. We lose access to the PR title here, which is why I replaced the PR title with a generic "sync: update CI config files" (which @mvdan suggested anyway).
As a future improvement, we might be able to regain access to some of the information if we restrict the merge method to squashing, but I haven't tried …
> run dispatch workflow when pushing to master

- templates/.github/workflows/go-test.yml
We recently turned down Codecov's verbosity by using the config suggested by the [Go Best Practice document](https://github.com/ipld/ipld/blob/master/best-practices/go-ci.md#using-code-coverage-tools). We can now afford to upload a coverage report for every test run.
> always upload coverage report to Codecov

- .github/workflows/copy-workflow.yml
- .github/workflows/github-users.json
IPFS and Filecoin already use separate GitHub users, which Andy created earlier today.
If everything works out, we'll also create separate GitHub users for all the other orgs. With this PR in place, all we have to do is update the user configuration in `github-users.json`.
> make it possible to use different GitHub users per GitHub org

- .github/workflows/copy-workflow.yml
For a demonstration of the problem, see https://github.com/libp2p/go-addr-util/pull/32/commits/9651346e5f362790f8d0cba1b1fc3ac8a268f0ab.
The copy workflow runs `go mod tidy` and `gofmt`, but with Go 1.15.x (don't ask me why that's the default version installed on GitHub Actions, I have no idea). The `go-check` workflow then runs these tools with Go 1.16.x, which might produce different results.
> use Go 1.16 to run go mod tidy, gofmt in copy workflow

- templates/.github/workflows/go-check.yml
Fixes #73.
If `go.mod` doesn't contain any dependencies, it's not necessary to have a `go.sum` file.
Unfortunately, this change will trigger a PR in all repos that we've deployed to so far.
> don't require go.sum in go-check workflow

- .github/workflows/copy-workflow.yml
Delaying merge until #74 is merged, in order to minimize the number of PRs we create.
> fix indent in copy workflow

- config.json
CI is currently broken anyways.
> chore: add go-merkledag

- .github/workflows/stale-repos.yml
Turns out we already have one deleted repo in our list (ipfs/go-ipfs-blockutil), and one archived one (ipfs/go-ipfs-cmdkit).
Sample run: https://github.com/protocol/.github/runs/2604478580?check_suite_focus=true
Future steps:
- Run this workflow on `pull_request` as well, but only only on newly added repos (if any).
- Create a PR that fixes `config.json` (this is probably overkill, we don't archive repos that often).
> add a cron workflow to find deleted repositories

- config.json
Depends on https://github.com/multiformats/go-multiaddr-fmt/pull/15.
> chore: add more multiformats repos

- templates/.github/workflows/go-test.yml
[Codecov 1.5.0](https://github.com/codecov/codecov-action/releases/tag/v1.5.0) moved the uploader script to the Action itself. That seems to be a safer approach than downloading it from the Codecov server.
> update the Codecov Action to v1.5.0

- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Some of our repos use git submodules. We need to tell the checkout action to clone submodules.
Example: https://github.com/multiformats/go-multibase/pull/43.
> checkout submodules (recursively)

- templates/.github/workflows/automerge.yml
That way, automerge won't trigger if:
* we added commits to the pull request that web3-bot opened, or
* we rebased the branch.
> only automerge if all commits were authored by web3-bot

- .github/workflows/check-3rd-party.yml
- .github/workflows/check-config.yml
- .github/workflows/copy-workflow.yml
- templates/.github/workflows/automerge.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
1. Name them. This means the status checks get nice names instead of filenames.
2. Split go checks into "staticcheck" and "basic" so we can run them in parallel.
> actions: enhance actions

- .github/workflows/check-3rd-party.sh
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Closes #89.
Note: Codecov coverage reports are only uploaded for the main repo. Fixing this will be more difficult.
> add support for repositories with multiple Go modules

- .github/workflows/copy-workflow.yml
A while back, we ran into GitHub's abuse detection mechanism when we tried to deploy updates to dozens of repos.
I expect that to happen again when we deploy to 100 repos now.
Yesterday, I opened https://github.com/peter-evans/create-pull-request/issues/855 and already got a reply there, including a branch to test. We can help test this change.
The plan is to first trigger a deployment, using the original version of _create-pull-request_, then merge this PR, and see if it helps.
> use the retry branch of peter-evans/create-pull-request

- config.json
Adds CI to `go-storethehash`: https://github.com/ipld/go-storethehash/issues/3
> chore: add ipld/go-storethehash

- .github/workflows/copy-workflow.yml
Update the copy workflow to remove `.gx` if it is present now that GX
has become redundant in favour of `go.mod`.
Relates to:
- https://github.com/whyrusleeping/gx
> Remove `.gx` on initial deployment

- config.json
Depends on https://github.com/libp2p/go-libp2p-quic-transport/pull/211.
> chore: add libp2p/go-libp2p-quic-transport

- .github/workflows/check-3rd-party.sh
- .github/workflows/check-config.sh
This is why CI didn't catch this malformed JSON document: https://github.com/protocol/.github/pull/146#discussion_r676722534.
> fail CI build when bash scripts error

- config.json
This repo is just a shim for backwards compat and has now been archived.
> chore: remove ipfs/go-hamt-ipld

- scripts/README.md
- scripts/get-repos/.gitignore
- scripts/get-repos/README.md
- scripts/get-repos/index.js
- scripts/get-repos/package-lock.json
- scripts/get-repos/package.json
I extracted the `get-repos` script from #30, because
1. it's better to have it committed to master than living in a PR and
2. I'd like to build on top of it, to add the repo health script (see #43).
> feat: add script to get a list of all repos

- config.json
I've added it to a new "on hold" tab in the tracker doc,
with the following reason:
Requires extra libraries for cgo.
The CI jobs simply fail now, as we don't support any customization of
the workflows, and Linux packages are missing.
We will likely support that kind of customization in the future, but not
right now.
> remove ipfs-shipyard/go-ipfs-desktop

- .github/workflows/copy-workflow.yml
Otherwise the copy workflow fails:
```
> Run for f in $(jq -r ".[]" <<< '"[ \".github/workflows/automerge.yml\", \".github/workflows/go-test.yml\", \".github/workflows/go-check.yml\" ]"'); do
jq: error (at <stdin>:1): Cannot iterate over string ("[ \".githu...)
```
> fix invalid quotes in copy workflow

- templates/.github/workflows/automerge.yml
Logically, this doesn't change anything. `automerge` depends on `automerge-check`, and `automerge-check` only runs when the PR was authored by web3-bot.
It does however prevent this job from being scheduled and then immediately being skipped.
> only run the automerge step if the PR was authored by web3-bot

- README.md
- templates/.github/workflows/go-check.yml
Fixes #123.
This PR introduces a new concept: Repositories can create a config file `.github/workflows/go-check-config.json` to enable an additional step in the `go-check` workflow: running `go generate ./...` to make sure that no files are modified or added.
This is a backwards-compatible change: If the config file doesn't exist, we don't run that step.
> run go generate if enabled in the config

- .github/workflows/copy-workflow.yml
Apparently deploying fails for a number of repositories because of this.
> update Go version in copy workflow, run go fix recursively

- templates/.github/workflows/go-test.yml
> include cross-package coverage in codecov

- templates/.github/workflows/go-test.yml
Codecov is doing - who would've thought - funny stuff with their uploader again: https://github.com/codecov/codecov-action/releases/tag/v2.1.0
> update Codecov action to v2.1.0

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
Fixes #105 (hopefully). To be honest, I have _no idea_ how many jobs we can run in parallel before triggering GitHub Action's abuse detection mechanism. We'll have to try this out.
> use concurrency groups to avoid running into GitHub Action's rate limits

- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- VERSIONING.md
- templates/.github/workflows/release-check.yml
- templates/.github/workflows/releaser.yml
Fixes #229.
Implementing the solution suggested in https://github.com/protocol/.github/issues/229#issuecomment-974815879.
> make it possible to cut release on non-default branches

- README.md
- config.json
- templates/.github/workflows/go-test.yml
This is an alternative way of using msys2bash on windows machines during go-test runs.
It prepends `C:/msys64/usr/bin` to `PATH`. After this, whenever we request `shell: bash`, `msys2`'s version will be picked ahead of `git`'s. 
With the original PR (https://github.com/protocol/.github/pull/221) the workflow wasn't able to find the paths specified in https://github.com/protocol/multiple-go-modules/blob/master/action.yml#L28:
```
New-Item : Cannot find path 'D:\a\_temp\setup-msys2\msys2.cmd' because it does not exist.
At line:1 char:1
+ New-Item -ItemType SymbolicLink -Path D:/a/_temp/setup-msys2/bash-or- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (D:\a\_temp\setup-msys2\msys2.cmd:String) [New-Item], …
```
> alternative: use msys2 on Windows

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
With current `concurrency` setup only the first and the last matrix job was run and the rest were cancelled with `Canceling since a higher priority waiting request for 'copy-*' exists`.
The [concurrency documentations](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) explains this as follows:
```
Any previously pending job or workflow in the concurrency group will be canceled.
```
I think settings `strategy.max-parallel: 1` in `copy-workflow` might do what we want it to which is to run all the matrix jobs within one copy-workflow instance sequentially: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
One thing to watch out for is if the job sequence will continue …
> Replace concurrency setup with max-parallel=1 strategy in copy-workflow

- templates/.github/workflows/go-test.yml
Reverts protocol/.github#210
https://github.com/golang/go/commit/c59b17e5a2244f7a99c440a07a1c174344da0ad8 is not included in go 1.16. We're going to revert the revert once we move to go 1.18.
> Revert "include cross-package coverage in codecov"

- .github/workflows/release-check.yml
This PR tries to address https://github.com/protocol/.github/issues/254
This PR makes sure that runs of `release-check` workflow succeed for PRs from forks BUT it does have to disable auto posting of the messages on such PRs. However, it makes the message easily discoverable/copyable from the workflow run. An idea for a future improvement would be to create something like `release-check-cron` that would loop over recently run `release-check`s in the repository and post comments to the PRs if they haven't been posted yet. That would be possible because a workflow that runs on cron schedule from master is allowed to have elevated privileges. 
- replaced uses of `github.event.pull_request.head.sha` with `HEAD` since, on PRs from forked repos, the former points at a sha from the fork(which is …
> make release-check pass on PRs from forked repositories

- config.json
See https://github.com/libp2p/go-addr-util/pull/44.
> chore: remove deprecated libp2p/go-addr-util

- config.json
Sorry, the release flow that was enabled replaces a "git tag; git push" operation, which takes me 1 second, with a PR, a 40 minute build and maintenance of a file with redundant information. And it does not generate an automatic changelog based on commit messages or publish a github release as I expected so it literally takes 0 work from me. All this is just adding crust that costs me time. I will re-enable this project when this changes.
> chore: remove go-ds-crdt

- .github/workflows/check-config.yml
- .github/workflows/check-yaml.yml
- README.md
- templates/.github/workflows/go-test.yml
Resolves #76 
This PR adds GitHub workflow that runs on PR in this repo which performs YAML linting. It gets the correct schema from https://www.schemastore.org/api/json/catalog.json (same as VS Code YAML extension).
I target `next` in this PR because I had to modify `go-test.yml` slightly to make the linter happy.
> check github actions yamls

- .github/workflows/check-3rd-party.sh
- configs/README.md
- configs/js.json
- templates/.github/workflows/js-test-and-release.yml
Resolves https://github.com/protocol/.github/issues/235
Resolves https://github.com/protocol/.github/issues/273
In this PR I create a new JSON config for JS repos, copy the JS CI workflow created by @achingbrain to the templates directory and configure unified CI for JS repositories that were mentioned here https://github.com/protocol/.github/issues/273#issue-1097614645. 
*This is now happily running on [typescript](https://github.com/libp2p/js-libp2p-crypto), [pure-ESM](https://github.com/ipfs/js-blockstore-core), [node-js only](https://github.com/libp2p/js-libp2p-tcp) and [monorepo](https://github.com/libp2p/js-libp2p-interfaces) projects.* - https://github.com/protocol/.github/issues/273#issue-1097614645
> deploy JS unified CI script

- .github/workflows/automerge.yml
`v0.2.0` only accepts checks that conclude with `success`.
`v1.1.1` also accepts checks that conclude with `skipped`.
This is required for the JS workflow to be automergable because they execute some jobs conditionally (e.g. `release`). Until the next unified CI release, PRs from web3-bot in JS repos will have to be merged manually:
- https://github.com/libp2p/js-libp2p-tcp/pull/160
- https://github.com/libp2p/js-libp2p-interfaces/pull/145
- https://github.com/libp2p/js-libp2p-crypto/pull/235
- https://github.com/ipfs/js-blockstore-core/pull/15
> upgrade lewagon/wait-on-check-action to v1.1.1

- .github/actions/copy-workflow-versioning/action.yml
Resolves #264
It will add a `version.json` file with the following content in repos that don't have releases yet:
```
{
"version": ""
}
```
Do you think we should target `next` or `master` with this? If we target `master`, it will create new PRs but only in repos without `version.json` which shouldn't be too bad.
> always add a version.json file if it doesn't exist

- .github/workflows/release-check.yml
Resolves https://github.com/protocol/.github/issues/285
In this PR I propose to replace `INITIAL_RUN` check with `TAG_EXISTS` check in `release-check` workflow.
In the new setup, we will run the rest of the `release-check` workflow only if a git tag for `version` from `version.json` does NOT exist yet. 
In particular, if the `version` is an empty string, we will not execute the rest of the workflow.
> check if tag already exists in release-check

- templates/.github/workflows/go-test.yml
This will enable merging unified CI in `go-openssl` repo (see https://github.com/libp2p/go-openssl/pull/20). We need to be able to specify a custom PATH for 32bit windows build because it requires `/c/msys64/mingw32/bin` to be available. We cannot set it globally because 64bit windows builds need `/c/msys64/mingw32/bin` instead. As an alternative approach I tried setting `CC_FOR_windows_386` but the compiler calls other underlying tools (like `ld` for example) by name, I think, so if they're not on PATH, they cannot be found.
> allow specifying custom PATH for 386 arch

- configs/go.json
I'd like to fix https://github.com/ipfs/go-pinning-service-http-client/issues/14 and make release using unified CI.
First step is to add https://github.com/ipfs/go-pinning-service-http-client  here
> chore: add go-pinning-service-http-client

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/release-check.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Closes https://github.com/protocol/.github/issues/193
Todo:
> Update to go 1.18

- configs/go.json
I've noticed a couple of issues with the config during the recent release. This PR fixes them. 
`filecoin-project/go-commp-utils` cannot use Unified CI because it has a submodule and, sadly, it's not supported by our Go workflows currently. See https://github.com/filecoin-project/go-commp-utils/tree/master/extern
`filecoin-project/indexer-reference-provider` changed name to `filecoin-project/index-provider`
> Clean up configs/go.json after 2022-04-04 release

- templates/.github/workflows/js-test-and-release.yml
The new aegir release writes the coverage report into the default location so it will be found by codecov-action automagically - no need to specify a path as an arg, which doesn't work with monorepos anyway.
> fix: remove codecov directory

- .github/workflows/add-label-by-query.yml
Resolves https://github.com/protocol/.github/issues/40
This PR adds a workflow that accepts a [issue or pull reuqest query](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) and a label and adds that label to all the issue or pull requests matching the query.
If label is left blank, the workflow will just print the repository name with the owner and the number of the issue or pull request it would have added a label to.
*NOTE*: It will only be able to add labels to issues/PRs in repositories `web3-bot` was invited to.
> add a workflow that adds a label to content matching query

- templates/.github/workflows/go-test.yml
Fixes https://github.com/protocol/.github/issues/237
We dropped support for go 1.16, which means we can use `-shuffle` during go tests now.
> feat: use shuffle during go-tests (fixes #237)

- .github/actions/copy-workflow-go/action.yml
This PR ensures we take Go's advice on how to handle dependency resolution issues when we want previous Go versions to stay supported. See this for example:
```
github.com/ipfs/go-graphsync/tools imports
github.com/hannahhoward/cbor-gen-for imports
github.com/urfave/cli/v2 imports
github.com/cpuguy83/go-md2man/v2/md2man loaded from github.com/cpuguy83/go-md2man/v2@v2.0.0-20190314233015-f79a8a8ca69d,
but go 1.16 would select v2.0.0
github.com/ipfs/go-graphsync/allocator imports
github.com/ipfs/go-log/v2 imports
go.uber.org/zap tested by
go.uber.org/zap.test imports
go.uber.org/goleak loaded from go.uber.org/goleak@v1.1.11,
but go 1.16 would select v1.1.12
github.com/ipfs/go-graphsync/allocator imports
github.com/ipfs/go-log/v2 imports
go.uber.org/zap tested by
go.uber.org/zap.test imports …
```
> fix: dependency resolution problem in Go version upgrades

- templates/.github/workflows/go-check.yml
Hopefully, this will be enough to upgrade to Go 1.19.
Required by: https://github.com/protocol/.github/issues/362
> chore: upgrade staticcheck to 2022.1.3 (v0.3.3)

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/release-check.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Required by: https://github.com/protocol/.github/issues/362
Adds support for Go 1.19 and drops Go 1.17.
> change supported Go versions from 1.17 and 1.18 to 1.18 and 1.19

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
- README.md
This PR adds support for a new property `source_ref` in the repository targets. When `source_ref` is set, `Deploy` workflow will check out `protocol/.github` at said ref and copy the workflows from there instead of `github.ref` (the branch in which the workflow is running). 
If `source_ref` is not specified, `Deploy` workflow will act exactly as it did before i.e. it will check out `github.ref`.
We'd like to let users opt-in to Go 1.19 upgrade before we're able to perform the official release (https://github.com/protocol/.github/issues/362).
But I think this will become useful beyond this immediate need, e.g. for continuous testing of the `next` branch. 
```
Run actions/checkout@v2
with:
path: template-repo
ref: refs/heads/testing
```
```
Run actions/checkout@v2
with:
path: template-repo …
```
> feat: enable support for opting in to technical preview updates

- configs/go.json
What I did:
1. create the branch `preview` from `next`: https://github.com/protocol/.github/tree/preview ([diff](https://github.com/protocol/.github/compare/next...preview))
2. update `source_ref` in `go-libp2p`
Merging into master will trigger a deployment of the `preview` version.
Taking into account the discussion in https://github.com/protocol/.github/issues/367 we use a branch that is not `next` until we agree on a definitive naming.
> feat: add go-libp2p to preview

- .github/actions/copy-workflow-go/action.yml
Following up on https://github.com/protocol/.github/pull/366#issuecomment-1225751649
I tested the newly added part locally on `ipfs/go-ipfs-files` (note, that particular repo will require manual intervention anyway because it uses `ioutil.ReadDir` too but I think most other repos don't). 
Merging to `master` because it will only affect the repos with unmerged upgrades to Go 1.19.
> automate cleaning up deprecated io/ioutil

- .github/actions/copy-workflow-go/action.yml
`git commit` exists with `1` if it has nothing to commit - that's why we need to check if there's anything to commit ahead of time.
> hide goimport fix commit behind git diff check

- .github/actions/copy-workflow-go/action.yml
I looked through a couple of PRs that are still having issues with `ioutil` and it turns out that this simple replacement would work there because we only care about file names and the `os.ReadDir` results do offer that.
> feat: replace ioutil.ReadDir too

- templates/.github/workflows/js-test-and-release.yml
AFAICT the only breaking change is removal of `version` prop in favor of `node-version` but we're using the latter already - https://github.com/actions/setup-node/releases.
> chore: update setup-node to v3

- .github/workflows/stale-repos.yml
This fixes stale check on PRs. Previously, we didn't account for a situation where `configs/*.json` is modified but none of the targets are removed/added.
> do not exec stale repos check on empty config

- .github/workflows/stale-repos.yml
- configs/go.json
If I understand correctly, `preview` is currently behind `master`. We're currently running into build failures due to checkout action, the hope is that by upgrading to `checkout@v3`, these problems will go away.
Example run: https://github.com/libp2p/go-libp2p/actions/runs/3092737094/jobs/5004342667
> remove go-libp2p from preview

- README.md
- templates/.github/workflows/go-test.yml
Introduce an option to configure `go-test` to allow completely skipping `32-bit` tests.
Fixes #388
> Add option to skip `32-bit` go test

- templates/.github/workflows/js-test-and-release.yml
If `branches` is set to the default branch, it means CI will only run on a PR that targets the default branch.
Sometimes we have release branches like `/release/v1.0.0` which use use to backport fixes to previous versions - we still want CI to run on these backport PRs so change the PR branch target to run CI on PRs that target any branch.
> fix: update pull request target to use wildcard

- configs/go.json
Enable unified CI builds for `ipni/heyfil` go project; See:
- https://github.com/ipni/heyfil
> Enable unified CI for `ipni/heyfil` go project

- configs/go.json
We're putting `go-ds-pebble` on Unified CI updates from `next` branch (using https://github.com/protocol/.github#technical-preview feature) to be able to skip 32bit tests (https://github.com/protocol/.github/pull/412).
We're going to clear the `source_ref` setting so that `go-ds-pebble` gets updates from `master` again during the next major Unified CI release.
> use next as a source for go-ds-pebble

- templates/.github/workflows/js-test-and-release.yml
Node 16 is no longer lts, instead use `lts/*` as the version to always get active lts, version 18.x at the time of writing.
> fix: test on lts node

- configs/go.json
Add `indexstar` and `index-observer` from IPNI org to unified CI for
Golang.
> Add `indexstar` and `index-observer` to unified CI for Golang

- .github/workflows/release-check.yml
Resolves #394
By running go mod download before go release we won't include stdout related to dependency downloads in the comment.
> fix: run go mod download before go release

- templates/.github/workflows/js-test-and-release.yml
Reverts protocol/.github#428 - on second thoughts, release steps are controlled by the `"release"` script, no need to add a separate job here.
> Revert "feat: add step to publish docs during js release"

- .github/workflows/dispatch.yml
Resolves #374
We don't want to run dispatch in parallel because they would be overwriting each other.
> Run at most 1 dispatch job per ref

- .github/workflows/release-check.yml
Resolves #381 
This PR adds a check if `git tag | paste -sd , -` returns a non-empty string. It looks for a version to compare to only if the return value is non-empty.
> fix: check if git tag returns any results

- .github/workflows/release-check.yml
This PR modified `release-check.yml`. It changes it in the following ways:
- do not use global `GITHUB_ENV`
- do use steps' `GITHUB_OUTPUT`s
- do not use template expansion (`${{}}`) inside `run:` blocks
- do make other steps' outputs available to a step either through `env:` block or through `with:` block
As a result, we end up with a workflow where each step is explicitly given context. It is also given only what it requires. Finally, it is less prone to script/env var injection (we're taking in user input through `version.json@version`).
> use GHA template expansion only in env/arg in release-check workflow

- .github/actions/read-config/action.yml
- README.md
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Resolves #349
This PR allows configuring uCI to skip go-test on certain OSes by providing a list of OSes that should be skipped in `go-test-config.json` under `skipOSes` key.
If there's a match, the most time consuming steps of the workflow will be skipped. The job itself won't because that would require us to split the job in two, where one would be used only for figuring out whether the other should be skipped, and we don't want to introduce the overhead of starting up two jobs.
> feat: allow skipping go-test on certain OSes

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/automerge.yml
- .github/workflows/check-yaml.yml
- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- .github/workflows/tagpush.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
- templates/.github/workflows/js-test-and-release.yml
Updates GitHub Actions actions and Go modules versions ahead of the uCI release including Go 1.20.
> chore: udpate actions and go modules

- configs/go.json
there's an invite for web3-bot to the repo that needs to be approved first. it's not a member of the -saturn org. can try to get that fixed next week.
> Add caboose

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/release-check.yml
- configs/README.md
- configs/go.json
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
- templates/.github/workflows/release-check.yml
Resolves #111
This PR simplifies how Go versions are defined by making https://github.com/protocol/.github/blob/3104214787d953097a1d849fff039298e489f8a0/configs/go.json#L13-L15 the only place which explicitly states the version strings. All other places in which we referred to Go versions will transitively read from this config from now on.
It also describes all the steps that are required to bump Go version - i.e. update the version strings in the list.
> simplify Go version upgrade procedure

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/add-label-by-query.yml
- .github/workflows/automerge.yml
- .github/workflows/check-3rd-party.yml
- .github/workflows/copy-workflow.yml
- .github/workflows/create-prs.yml
- .github/workflows/dispatch.yml
- .github/workflows/releaser.yml
- .github/workflows/stale-repos.yml
- .github/workflows/tagpush.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
- templates/.github/workflows/js-test-and-release.yml
Things addressed in this PR:
- consistency: using `$` instead of `${}` where possible when accessing env variables
- security: not using dangerous `${{}}` inside `steps.*.run` blocks
- consistency: using `github.token` instead of `secrets.GITHUB_TOKEN`
- up-to-date: not using deprecated `set-output`
- consistency: using `to/fromJSON` instead of `to/fromJson`
- consistency: not using obsolete `${{}}` in the `steps.*.if` blocks
> Go through all the workflows and clean them up ahead of the next major release

- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- VERSIONING.md
Resolves #228 by making release workflows create GitHub Releases.
This PR makes release-check create a **draft** GitHub Release and include a link to it in a comment IF the PR is **NOT** from fork. Otherwise, it suggests creating a draft GitHub Release in the comment.
This PR makes releaser either publish the draft GitHub Release if it exists or create a GitHub Release otherwise.
> feat: create gh releases in release-check/releaser workflows

- README.md
- templates/.github/workflows/go-test.yml
Resolves #460
By setting `GO*FLAGS` as top-level env variables, we allow them being overwritten in `go-test-setup` action. In particular, this will allow disabling coverage on one or all OSes.
> feat: allow disabling coverage and shuffle

- scripts/get-repos/index.js
- scripts/get-repos/package-lock.json
- scripts/get-repos/package.json
- scripts/health.sh
Depends on #145, as it used the `get-repos` script.
This is the script that was used to generate the [Go Repo Health](https://docs.google.com/spreadsheets/d/1Vwk-OUKXXNQkp4BkOoMndLylnJRW7a2c_mmvXu6jIj8/edit#gid=0) spreadsheet, now with an added column indicating if web3-bot already created a PR or not.
> add the script used check the Go repo health

- .github/workflows/create-prs.yml
With https://github.com/libp2p/github-mgmt/pull/125 and https://github.com/libp2p/github-mgmt/pull/93 in place, we should follow semantic PRs guidelines here.
> fix: uCI PRs should follow semantic PRs guidelines

- .github/workflows/releaser.yml
Resolves #481
This resolves a serious bug where releaser always creates tags from the default branch. This is because we started using GitHub Release publishing for tag creation with the latest major uCI release. GitHub Release publishing cannot be configured to create tags from branches other than default. That's why we should first create a tag, and only then publish a GitHub Release that references that tag.
This PR makes sure we create a tag for the correct SHA and only then publishes a GitHub Release for that tag.
I released `galargh/go-libp2p@v0.26.2` using the version of the workflow from this branch.
- release PR https://github.com/galargh/go-libp2p/pull/1
- release tag https://github.com/galargh/go-libp2p/tree/v0.26.2
- release branch …
> fix: push tag explicitly before publishing the release

- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
This should ensure we specify correct release notes. With this change, we can get rid of explicit tag creation because GitHub release publish will now know what sha to use to create a tag on publish (I didn't add it earlier because I didn't know this feature existed).
- Tag created with these workflows: https://github.com/galargh/go-libp2p/tree/v0.26.3
- Releaser workflow run: https://github.com/galargh/go-libp2p/actions/runs/4301371990/jobs/7498576592
- Release Check workflow run: https://github.com/galargh/go-libp2p/actions/runs/4301337709
- Release: https://github.com/galargh/go-libp2p/releases/tag/v0.26.3
- Release PR: https://github.com/galargh/go-libp2p/pull/3
> fix: specify target for github release

- templates/.github/workflows/js-test-and-release.yml
To use in a project, declare npm scripts similar to `test:firefox` and `test:firefox-webworker`:
```js
// package.json
"scripts": {
// existing lines:
"test:firefox": "aegir test -t browser -- --browser firefox",
"test:firefox-webworker": "aegir test -t webworker -- --browser firefox",
// add the lines below:
"test:webkit": "aegir test -t browser -- --browser webkit",
"test:webkit-webworker": "aegir test -t webworker -- --browser webkit"
}
```
Runs webkit tests on MacOS X and Linux, not sure if both are necessary tbh.
> Adds jobs for testing webkit and webkit-webworker

- templates/.github/workflows/js-test-and-release.yml
Fixes yaml syntax errors introduced in https://github.com/protocol/.github/pull/487
The automerge jobs for this [failed](https://github.com/ipfs/helia-ipns/actions/runs/4424888455) yet the [PRs were still merged](https://github.com/ipfs/helia-ipns/pull/9).
> fix: fix js test and release workflow

- templates/.github/workflows/automerge.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
- templates/.github/workflows/js-test-and-release.yml
- templates/.github/workflows/release-check.yml
- templates/.github/workflows/releaser.yml
- templates/.github/workflows/tagpush.yml
This PR introduces concurrency groups to all the workflows distributed via uCI. The concurrency groups work as follows:
- pull_request: if a new commit is pushed to the PR, any in-progress runs of the workflow for that PR are going to be cancelled
- push: no change, workflow runs will continue running until the end
- deployed the change to a test repo: https://github.com/protocol/.github-test-target/pull/54
> feat: set concurrency on all the workflow templates

- .github/workflows/copy-workflow.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
This PR modifies the uCI templates in such a way that we don't duplicate as much work. In particular, `go-test` and `go-check` will keep running on all the pull requests BUT they will now run only on pushes to protected branches rather than on all the pushes.
> feat: run go test/check on PR or push to default/protected branch

- README.md
- templates/.github/workflows/go-test.yml
This is an alternative to https://github.com/protocol/.github/pull/513 which keeps the defaults as they were while allowing to opt-out of -v and -shuffle=on flags.
> feat: make -v and -shuffle configurable options

- .github/workflows/js-test-and-release.yml
- templates/.github/workflows/js-test-and-release.yml
We can use `github.event.repository.default_branch` instead.
> chore: remove custom default_branch input from js-test-and-release

- .github/actions/read-config
- .github/actions/read-config/action.yml
- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- .github/workflows/tagpush.yml
- scripts/copy-legacy-workflows-and-actions.sh
This is a follow-up to https://github.com/protocol/.github/pull/542. Unfortunately, GHA doesn't understand symlinks :( I still think it's worth pursuing the restructure because it brings more clarity to the unified CI repo.
> fix: copy already distributed shared workflows and actions to their old locations

- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
Resolves https://github.com/protocol/.github/issues/530
The fix requires updating gh-release-action to the version from https://github.com/galargh/action-gh-release/pull/1.
- https://github.com/protocol/.github-test-target/actions/runs/5623307935 released https://github.com/protocol/.github-test-target/releases/tag/v0.4.9 as not latest because https://github.com/protocol/.github-test-target/releases/tag/v0.5.0 already existed
- https://github.com/protocol/.github-test-target/actions/runs/5624117780 released https://github.com/protocol/.github-test-target/releases/tag/v0.5.1 as latest
> fix: marking releases as latest

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
With this change in place we'll be able to trigger deploys by repo names. We achieve that by moving the config extraction logic from dispatch to deploy.
> feat: trigger copy workflow with a list of repo names

- scripts/copy-templates.sh
- shared/.github/workflows/process.yml
- templates/header.yml
With this change, Unified CI will start defaulting to performing dependabot-like updates only. I.e. it will only try to update dependency versions but the rest of the workflows will stay intact if they already exist. We'll be able to opt-out of this behaviour by adding `force: true` flag to the `uci.yml`.
If dependabot is configured to update GitHub Actions in a repository, we're going to skip web3-bot updates.
> feat: by default perform dependabot-like updates only

- configs/go.json
Permission to web3-bot has already been granted. Add the repos to the unified CI build.
> Enable unified CI for `boostly` and `telefil` in filecoin-shipyard
