- workflow-templates/go-test.yml
> drop Go 1.14, add Go 1.16

- workflow-templates/go-check.yml
- workflow-templates/go-test.yml
> use commit hash to include 3rd party GitHub Actions

- workflow-templates/automerge.yml
> use squash merge when auto-merging

- LICENSE-APACHE
- LICENSE-MIT
Let's all be good citizens of the internet and put a license on our code, shall we?
> add a license

- README.md
Depends on #10.
Not sure if my text is really understandable, but at least it's something. Would be happy about suggestions how to improve it.
> add a README with a high-level description

- .github/workflows/copy-workflow.yml
On first deployment, both PR title and commit msg will be: `add XYZ workflow`.
On all subsequent deployments, the PR title and the commit msg will include the title of the PR in this repository (as before).
> set a more useful commit msg and PR title for first deployments

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
> only pass github.event from the dispatch to the copy workflow

- .github/workflows/copy-workflow.yml
Just spotted a wee typo while reviewing :)
> Typo fix in copy-workflow logs.

- .github/workflows/copy-workflow.yml
The git command determines the number of commits on the current branch after `origin/<current branch>`.
> simplify PR generation in copy workflow

- templates/.github/workflows/go-check.yml
Fixes #26.
Sample output in https://github.com/marten-seemann-test/target/pull/53/files.
> run gofmt in go-check

- .github/workflows/copy-workflow.yml
> fix broken condition for creating PRs

- .github/workflows/check-config.yml
- config.json
`config.json` will be a long file (hundreds of lines). Make sure that it's sorted.
> check that config.json is sorted alphabetically

- .githooks/README.md
- .githooks/pre-commit
- .github/workflows/check-config.sh
- .github/workflows/check-config.yml
> make it possible to run the check-config script as a pre-commit hook

- templates/.github/workflows/go-test.yml
> update Codecov GitHub Action to v1.4.1

- templates/.github/workflows/go-check.yml
https://staticcheck.io/changes/2021.1
> update staticcheck to 2021.1 (v0.2.0)

- config.json
Address storetheindex issue: ["CI for code quality #11"](https://github.com/filecoin-project/storetheindex/issues/11)
> Add filecoin-project/storetheindex to participating repos

- config.json
cleanup done in https://github.com/ipld/go-ipld-schema/pull/12
> Add ipld/go-ipld-schema

- .github/workflows/copy-workflow.yml
> only run gofmt and go mod tidy on initial deployment

- README.md
> README: stop suggesting autorebase

- .github/workflows/dispatch.yml
- config-testing.json
> initialize the "testing" branch setup

- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
See https://github.com/protocol/multiple-go-modules/pull/3.
> update protocol/multiple-go-modules to v1.1

- templates/.github/workflows/go-test.yml
Codecov has a new uploader (again!).
Aren't we all happy about new Codecov uploaders?
> update the Codecov Action to v2.0.1

- templates/.github/workflows/go-test.yml
> upload coverage files for all modules to Codecov

- .github/workflows/copy-workflow.yml
- .github/workflows/dispatch.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
> teach copy-workflow to bump go.mod's version

- config.json
Add CI to: https://github.com/filecoin-project/indexer-reference-provider
> chore: add filecoin-project/indexer-reference-provider

- config.json
Fixes:
- https://github.com/ipfs-shipyard/w3rc/issues/19
> Integrate unified CI with w3rc

- config.json
Project:
- https://github.com/filecoin-project/go-legs
> chore: add filecoin-project/go-legs

- templates/.github/workflows/go-check.yml
https://github.com/dominikh/go-tools/releases/tag/2021.1.2
> update staticcheck to 2021.1.2 (v0.2.2)

- README.md
GitHub Actions finally fixed the issue, see https://github.com/actions/runner/issues/834#issuecomment-9567794.
This reverts #202.
> use "if:" for OS-specific additional setup steps

- templates/.github/workflows/go-test.yml
> Revert "Revert "include cross-package coverage in codecov""

- .github/workflows/release-check.yml
Possible improvement suggested here: https://github.com/protocol/.github/pull/257#discussion_r773182260
> do not archive release check message

- templates/.github/workflows/js-test-and-release.yml
This should be `DOCKER_TOKEN` and not `DOCKER_USERNAME`
> fix: docker env var name is wrong

- configs/go.json
> configs: remove deprecated go-ipld-prime-proto

- configs/js.json
These repos all have the shiny new auto-deploy scripts so should be managed by `web3-bot`.
> add ipfs repos to unified ci

- configs/js.json
Adds the latest batch of repos.
> Add more js repos to unified ci

- configs/go.json
Adding https://github.com/filecoin-project/eudico/
> adding eudico to CI

- configs/go.json
> Revert "adding eudico to CI"

- configs/go.json
should be working now, as of https://github.com/ipld/go-ipld-prime/pull/409
> add ipld/go-ipld-prime

- CODEOWNERS
I also enabled auto review assignment on @protocol/ipdx so we're going to start getting notifs about new PRs here.
> chore: add ipdx as uCI codeowners

- templates/.github/workflows/go-test.yml
Following up on https://discord.com/channels/806902334369824788/979025498816520292/979046186143072296
> Upgrade codecov-action to v3.1.0

- .github/actions/copy-workflow-go/action.yml
- .github/workflows/automerge.yml
- .github/workflows/check-3rd-party.yml
- .github/workflows/check-config.yml
- .github/workflows/check-yaml.yml
- .github/workflows/copy-workflow.yml
- .github/workflows/create-prs.yml
- .github/workflows/dispatch.yml
- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- .github/workflows/stale-repos.yml
- .github/workflows/tagpush.yml
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
- templates/.github/workflows/js-test-and-release.yml
> Upgrade GitHub actions

- configs/go.json
Fixing issues raised by https://github.com/protocol/.github/runs/7972743573?check_suite_focus=true
> chore: removed archived repos from go config

- configs/js.json
Following https://www.notion.so/pl-strflt/Publishing-npm-packages-24915dd636a945bf9858f8c04e9c6758#5f6814bb7beb4ef3976949e11f734488
> feat: enable unified CI for js-kubo-rpc-client

- configs/js.json
> chore: add dns-over-http-resolver repo

- configs/js.json
This is part of the JS IPLD ESM migration: https://github.com/ipld/ipld/issues/224
Do we need to merge the [aegir changes](https://github.com/multiformats/js-multiformats/pull/196) into js-multiformtats before or after this PR gets merged?
cc @achingbrain @rvagg
> Add js-multiformats to unified-ci

- configs/go.json
> Add go-libipfs

- templates/.github/workflows/js-test-and-release.yml
During the release job, run the `docs` npm script if present.
> feat: add step to publish docs during js release

- configs/js.json
> Add libp2p interop suite to Unified CI

- templates/.github/workflows/go-check.yml
This can be helpful for debugging / monitoring what's going on.
> make go generate print the commands it executes

- README.md
> docs: document how to access github token in setup actions

- configs/go.json
Enable go unified CI pipeline for `ipni/depute` repo.
> Enable go unified CI for `ipni/depute`

- configs/go.json
Part of https://github.com/ipfs/bifrost-gateway/issues/1
I've already added `web3-bot`, it has write access to the repo.
> Add ipfs/bifrost-gateway

- configs/go.json
- templates/.github/workflows/go-check.yml
- templates/.github/workflows/go-test.yml
Merge only when we're all ready for proceeding with the final release.
> clean up where source ref was set to next

- configs/go.json
requires changes introduced in https://github.com/protocol/.github/pull/472
> update go-fil-commp-hashhash from next

- configs/go.json
See:
- https://github.com/filecoin-project/lassie-event-recorder
> Add `lassie-event-recorder` to Go unified CI

- .github/workflows/check-3rd-party.sh
- .github/workflows/check-yaml.yml
We can use v1 tag now that the action is properly released.
> chore: use pl-strflt/validate-yaml-schema@v1

- configs/go.json
Automate CI for ipni-cli repo.
> Add repo ipni/ipni-cli

- templates/.github/workflows/js-test-and-release.yml
Check typescript in documentation as part of linting
Refs: https://github.com/libp2p/js-libp2p/pull/1505/files
> adds doc-check command to js UCI

- configs/go.json
For https://github.com/plprobelab/go-kademlia/issues/28
> Add plprobelab/go-kademlia

- configs/go.json
See:
- https://github.com/filecoin-project/motion
> Set up unified CI for project Motion

- configs/go.json
singularity is used as a client pushing data into filecoin.
cc @masih  @xinaxu
> Add Singularity

- configs/go.json
See:
- https://github.com/FILCAT/ribs
> Add `FILCAT/ribs` to unified go CI setup

- .github/workflows/copy-workflow.yml
With the ability to override the defaults when calling the workflow, we'll be able to modify files selectively.
> feat: allow selective copy on files

- .github/workflows/list-repositories.yml
e.g. https://github.com/protocol/.github/actions/runs/5682559391/job/15401205245
> feat: add mainenance workflow for listing target repositories
